export const interestTypes = {
  art: "art",
  computers: "computers",
  cooking: "cooking",
  DIY: "DIY",
  education: "education",
  fitness: "fitness",
  hiking: "hiking",
  history: "history",
  IT: "IT",
  literature: "literature",
  music: "music",
  politics: "politics",
  science: "science",
  sightseeing: "sightseeing",
  sports: "sports",
  travelling: "travelling",
  yoga: "yoga",
};

export enum InterestEnum {
  art = "art",
  computers = "computers",
  cooking = "cooking",
  DIY = "DIY",
  education = "education",
  fitness = "fitness",
  hiking = "hiking",
  history = "history",
  IT = "IT",
  literature = "literature",
  music = "music",
  politics = "politics",
  science = "science",
  sightseeing = "sightseeing",
  sports = "sports",
  travelling = "travelling",
  yoga = "yoga",
}
